### ISSUE TITLE
Terraform 0.12

### ISSUE THREAD

**Issue by mud5150** [OctopusDeploy/HCLParser#3]
I wanted to see if you guys could share how much priority you'll have to update this library to support the HCL changes coming with Terraform 0.12. Are there plans to have octopus (and in effect this library) ready by the time 0.12 is released or do you think it will lag behind significantly?

**Comment by mcasperson** [comment]
Hi @mud5150 

Sorry for the late reply, but HCL 2 support has been added with a recent pull request. We're in the process of integrating it into Octopus for the 2020.5 release.
